language: python
env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=disk
matrix:
  include:
  - dist: xenial
    os: linux
    python: 3.7
    env: TOXENV=py37,py27
  - os: osx
    language: generic
    env:
    - TOXENV=py37
    - GITHUB_UPLOAD=yes

# install python3 with homebrew on osx.
before_install:
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update ; brew upgrade python; export PATH=/usr/local/bin:$PATH; fi;
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install python; export PATH=/usr/local/bin:$PATH; fi;

install: python3 -m pip install -r requirements.dev.txt
script: tox

# Deploy to github releases, and pypi.
# https://docs.travis-ci.com/user/deployment/
before_deploy:
  - python3 setup.py sdist bdist_dmg
deploy:
  - provider: releases
    api_key:
      secure: aYvqjWrenc0OEHcECfOuqdr/p+VdclpcNINd1vcQ+WdPR0b1uSP171baQIQa0IQqVh+Egn6tYzxcumlsZTgnFVjPGdYP95QhBIFVLVJskO+a/jxL1uJMT0O+GsZL4EYyy/9RZn6RzagvrQSTkCQI14eVP9F957295ZzevS4q8ZsghiJe0HoavtqRCcKsw/AznZV+c0vwks7qA+jiH9kMqtyoqRfgOFV7e76vRfLE40RjYGfh9tNvo8BWlWcxfx+H190OXncZoQs/ML8jHgIajd3bSTtb/83TFjmkvkmUqMiuCJt3yZcOewprHcX3HEicZ8F5ImLDtqeW5VqMFUwiY2pvVWKZRnaR8tT+YlbbqK8VMR/JDCj8sLeA9cNLmp3KzbBciy+FmmHnY3QuNMebMeCxJQYk/AIBzlSdf/7U3WTrRX33qlCn5m3zqM7/swCnWw+mrZCmOHulGPlG4ykOJGo8S1Fi5erIvj3ZFGG3T2d8+JdfzOi32bA7623qxFyNDW2xpl1wZFT+6jL9WYzz9iTB0oA2RPxFYGCG5U6I5TTktVq3wl97oaedKcBZhnPdu4Bh2NnDiBk71FJtY197u8xiQ1iFI0kYnU6YjLP2BQM3HeCZu0qrXhl+M5rQCN6LHy9bKQJPe2hxoB3QLUzmmpJRZmS5/vIODbNrBreWEkY=
    file:
      - build/*.dmg
      - dist/*.tar.gz
    draft: true
    on:
      all_branches: true
      # branches:
      #   only:
      #     - master
      tag: true
      repo: pygame/stuntcat
      condition: $GITHUB_UPLOAD = yes
