
language: python

# these are so the tests can run on travis headless.
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - dist: xenial
      os: linux
      python: 3.7
      env: TOXENV=py37
    - os: osx
      python: 2.7
      env: TOXENV=py27
    - os: windows
      python: 3.7
      env: TOXENV=py37

install: pip install tox

script: tox
