environment:

  matrix:
    - TOXENV: py37
      PYTHON: "C:\\Python37-x64"

    - TOXENV: py27
      PYTHON: "C:\\Python27"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install -r requirements.dev.txt"

test_script:
  - "build.cmd %PYTHON%\\python.exe -m tox"

