build: false

environment:
  matrix:
    - TOXENV: py37
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

    - TOXENV: py27
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.0"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install -r requirements.dev.txt"

test_script:
  - "build.cmd %PYTHON%\\python.exe -m tox"

