build: false

environment:
  matrix:
    - TOXENV: py37
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

    - TOXENV: py27
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.0"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "%PYTHON%\\python.exe --version"

# tox installs stuff itself.
install:
  # We need wheel installed to build wheels
  # - "%PYTHON%\\python.exe -m pip install -r requirements.dev.txt"
  - "%PYTHON%\\python.exe -m pip install tox"

test_script:
  - "%PYTHON%\\python.exe -m tox"
